### ISSUE TITLE
Clarification on `visit_id`

### ISSUE THREAD

**Issue by manuelburger** [som-shahlab/ehrshot-benchmark#11]
Dear EHRSHOT Team

Thank you very much for releasing such an awesome dataset and model. 

I started looking into the data (`data/ehrshot.csv`) and was curious where I could learn more about the nature of the `visit_id`. As I understand from the task descriptions and the intuitive understanding of a `visit_id`, a visit would be a single admission / stay at the hospital in any department.

However for many patients I find strongly overlapping time-periods for visits of the same patient, sometimes visits are even strict subsets of other visits in terms of the time-span that they cover.

Example here for one patient where I print the minimum and the maximum `start` time for each row in a visit for a given patient.
```
For patient_id == 115967095

Visit 31251999.0: 2008-10-07 23:56:00 - 2008-11-03 14:34:00
Visit nan: NaT - NaT
Visit 31315593.0: 2008-10-15 06:00:00 - 2008-10-15 11:07:00
Visit 31255748.0: 2008-10-08 23:59:00 - 2008-10-08 23:59:00
Visit 31278368.0: 2008-10-11 13:04:00 - 2008-10-11 13:17:00
Visit 31275860.0: 2008-10-11 19:43:00 - 2009-04-25 16:29:00
```

As such I find the `visit_ids` are not suitable to use as indicators to build a sequence of visits from. Is that correct? Could you clarify?

Add 1): On a related note, I would also highly encourage to export / store `visit_id` as an integer, the currently accessible data stores them as floats.

Add 2): Also I found that about 50% of the entries actually are missing a `visit_id` entirely. Is there any rational on how to interpret this?

**Comment by Miking98** [comment]
Hi @manuelburger ! 

My sincere apologies for the delay here, and thank you for taking a detailed look at the dataset.

Yes, the `visit_id` property is a bit messy. This is an unfortunate artifact of our source dataset, which itself is a conversion from Epic Clarity => OMOP CDM. We tried making minimal additional assumptions in our transformation from OMOP CDM => EHRSHOT and left these visit IDs as provided. 

For the EHRSHOT labeling functions, we use a couple other indicators to get better visit definitions. Namely, we use: (1) the `omop_table` field; (2) the actual code of the visit. 

To be specific...
* For **ICU admissions**, we (1) filter down to `omop_table = visit_detail` ([see here](https://github.com/som-shahlab/femr/blob/51a43019095c033eeffa653ec46cc4c6c6a60f5a/src/femr/labelers/omop.py#L169)) and (2) that the visit's code is a `CARE_SITE/XXX` ([see here](https://github.com/som-shahlab/femr/blob/51a43019095c033eeffa653ec46cc4c6c6a60f5a/src/femr/labelers/omop.py#L61)).
* For **inpatient admissions**, we filter down to `omop_table = visit_occurrence` ([see here](https://github.com/som-shahlab/femr/blob/51a43019095c033eeffa653ec46cc4c6c6a60f5a/src/femr/labelers/omop.py#L208)) and (2) that the visit's code is `Visit/IP` ([see here](https://github.com/som-shahlab/femr/blob/51a43019095c033eeffa653ec46cc4c6c6a60f5a/src/femr/labelers/omop.py#L48))
* For **outpatient admissions**, we filter down to `omop_table = visit_occurrence` ([see here](https://github.com/som-shahlab/femr/blob/51a43019095c033eeffa653ec46cc4c6c6a60f5a/src/femr/labelers/omop.py#L191)) and (2) that the visit's code is `Visit/OP` ([see here](https://github.com/som-shahlab/femr/blob/51a43019095c033eeffa653ec46cc4c6c6a60f5a/src/femr/labelers/omop.py#L52))

To answer your other questions:
1) Yes, agreed the `int` type makes more sense. We exported these from pandas dataframes which only support NaNs as floats, hence why they are floats in the current data dump.
2) Yes, some events aren't mapped to visits. This can be due to a number of reasons (visits dropped in the ETL from Epic Clarity => OMOP CDM => EHRSHOT, event type not being associated with an individual visit, etc.)

**Comment by manuelburger** [comment]
I can understand the trade-offs and I think you're choices are very reasonable. Thank you very much for the detailed reply @Miking98 and thanks again for doing the work to share such an awesome dataset, keep it going!

**Comment by Miking98** [comment]
Thank you @manuelburger for the thoughtful comment, and pease let me know if you have any other questions as you explore the data!
